-- REST_INFO 
-- REST_REVIEW
-- REST_ID, REST_NAME, FOOD_TYPE, VIEWS, FAVORITES, 
SELECT B.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS,
ROUND(AVG(B.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW B JOIN REST_INFO A ON B.REST_ID = A.REST_ID
GROUP BY A.REST_ID
HAVING A.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, A.FAVORITES DESC
