-- 총매출내놔
-- FOOD_PRODUCT 식품 정보 테이블 / 식품ID 식품 이름, 식품 코드 카테고리 가격
-- FOOD_ORDER 식품 주문 정보 / 주문ID 식품ID, 주문량, 생산일자, 입고일자, 출고일자, 공장 ID, 창고 ID

# SELECT IN_DATE FROM FOOD_ORDER
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN FOOD_ORDER O
ON P.PRODUCT_ID = O.PRODUCT_ID
WHERE YEAR(O.PRODUCE_DATE) = 2022 AND MONTH(O.PRODUCE_DATE) = 5
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID

