-- 도서 정보, 저자 정보
# SELECT A.BOOK_ID, B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
# FROM (SELECT * FROM BOOK WHERE CATEGORY='경제')A JOIN AUTHOR B 
# ON A.AUTHOR_ID = B.AUTHOR_ID
# ORDER BY A.PUBLISHED_DATE 

SELECT A.BOOK_ID, B.AUTHOR_NAME, DATE_FORMAT(A.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE
FROM 
(SELECT *
 FROM BOOK
 WHERE CATEGORY='경제')A
JOIN AUTHOR B
ON A.AUTHOR_ID=B.AUTHOR_ID
ORDER BY A.PUBLISHED_DATE ASC;